
import { Language, Voice } from './types';

export const PREBUILT_VOICES: Voice[] = [
  // Female-leaning Voices
  { id: 'kore', name: 'Kore', description: 'Bright & Clear', gender: 'Female' },
  { id: 'zephyr', name: 'Zephyr', description: 'Soft & Gentle', gender: 'Female' },
  { id: 'aoede', name: 'Aoede', description: 'Melodic & Sweet', gender: 'Female' },
  { id: 'leda', name: 'Leda', description: 'Professional & Warm', gender: 'Female' },
  { id: 'callirrhoe', name: 'Callirrhoe', description: 'Expressive', gender: 'Female' },
  { id: 'despina', name: 'Despina', description: 'Calm & Steady', gender: 'Female' },
  { id: 'erinome', name: 'Erinome', description: 'Youthful', gender: 'Female' },
  { id: 'laomedeia', name: 'Laomedeia', description: 'Formal', gender: 'Female' },
  { id: 'pulcherrima', name: 'Pulcherrima', description: 'Elegant', gender: 'Female' },
  { id: 'vindemiatrix', name: 'Vindemiatrix', description: 'Authoritative', gender: 'Female' },

  // Male-leaning Voices
  { id: 'puck', name: 'Puck', description: 'Fast & Energetic', gender: 'Male' },
  { id: 'charon', name: 'Charon', description: 'Deep & Resonant', gender: 'Male' },
  { id: 'fenrir', name: 'Fenrir', description: 'Smooth & Mature', gender: 'Male' },
  { id: 'orus', name: 'Orus', description: 'Direct & Clear', gender: 'Male' },
  { id: 'iapetus', name: 'Iapetus', description: 'Strong & Warm', gender: 'Male' },
  { id: 'enceladus', name: 'Enceladus', description: 'Bold', gender: 'Male' },
  { id: 'alnilam', name: 'Alnilam', description: 'Crisp', gender: 'Male' },
  { id: 'achernar', name: 'Achernar', description: 'Friendly', gender: 'Male' },
  { id: 'rasalgethi', name: 'Rasalgethi', description: 'Rich Tone', gender: 'Male' },
  { id: 'schedar', name: 'Schedar', description: 'Dramatic', gender: 'Male' },
  { id: 'umbriel', name: 'Umbriel', description: 'Serious', gender: 'Male' }
];

export const LANGUAGES: Language[] = [
  { code: 'bn-BD', name: 'Bengali', nativeName: 'বাংলা' },
  { code: 'en-US', name: 'English', nativeName: 'English' },
  { code: 'hi-IN', name: 'Hindi', nativeName: 'हिन्दी' },
  { code: 'es-ES', name: 'Spanish', nativeName: 'Español' },
  { code: 'fr-FR', name: 'French', nativeName: 'Français' },
  { code: 'de-DE', name: 'German', nativeName: 'Deutsch' },
  { code: 'it-IT', name: 'Italian', nativeName: 'Italiano' },
  { code: 'ja-JP', name: 'Japanese', nativeName: '日本語' },
  { code: 'ko-KR', name: 'Korean', nativeName: '한국어' },
  { code: 'pt-BR', name: 'Portuguese', nativeName: 'Português' },
  { code: 'ru-RU', name: 'Russian', nativeName: 'Русский' },
  { code: 'zh-CN', name: 'Chinese', nativeName: '中文' },
  { code: 'ar-SA', name: 'Arabic', nativeName: 'العربية' },
  { code: 'tr-TR', name: 'Turkish', nativeName: 'Türkçe' },
  { code: 'vi-VN', name: 'Vietnamese', nativeName: 'Tiếng Việt' },
  { code: 'th-TH', name: 'Thai', nativeName: 'ไทย' },
  { code: 'nl-NL', name: 'Dutch', nativeName: 'Nederlands' },
  { code: 'sv-SE', name: 'Swedish', nativeName: 'Svenska' },
  { code: 'pl-PL', name: 'Polish', nativeName: 'Polski' },
  { code: 'id-ID', name: 'Indonesian', nativeName: 'Bahasa Indonesia' },
  { code: 'da-DK', name: 'Danish', nativeName: 'Dansk' },
  { code: 'fi-FI', name: 'Finnish', nativeName: 'Suomi' },
  { code: 'no-NO', name: 'Norwegian', nativeName: 'Norsk' },
  { code: 'el-GR', name: 'Greek', nativeName: 'Ελληνικά' },
  { code: 'he-IL', name: 'Hebrew', nativeName: 'עבריত' },
  { code: 'ta-IN', name: 'Tamil', nativeName: 'தமிழ்' },
  { code: 'te-IN', name: 'Telugu', nativeName: 'తెలుగు' },
  { code: 'ml-IN', name: 'Malayalam', nativeName: 'മലയാളം' },
  { code: 'kn-IN', name: 'Kannada', nativeName: 'ಕನ್ನಡ' },
  { code: 'gu-IN', name: 'Gujarati', nativeName: 'ગુજરાતી' },
  { code: 'mr-IN', name: 'Marathi', nativeName: 'मराठी' },
  { code: 'pa-IN', name: 'Punjabi', nativeName: 'ਪੰਜਾਬੀ' },
  { code: 'ur-PK', name: 'Urdu', nativeName: 'اردو' },
  { code: 'fa-IR', name: 'Persian', nativeName: 'فارسی' },
  { code: 'uk-UA', name: 'Ukrainian', nativeName: 'Українська' },
  { code: 'ro-RO', name: 'Romanian', nativeName: 'Română' },
  { code: 'hu-HU', name: 'Hungarian', nativeName: 'Magyar' },
  { code: 'cs-CZ', name: 'Czech', nativeName: 'Čeština' },
  { code: 'sk-SK', name: 'Slovak', nativeName: 'Slovenčina' },
  { code: 'bg-BG', name: 'Bulgarian', nativeName: 'Български' },
  { code: 'hr-HR', name: 'Croatian', nativeName: 'Hrvatski' },
  { code: 'sr-RS', name: 'Serbian', nativeName: 'Српски' },
  { code: 'sl-SI', name: 'Slovenian', nativeName: 'Slovenščina' },
  { code: 'et-EE', name: 'Estonian', nativeName: 'Eesti' },
  { code: 'lv-LV', name: 'Latvian', nativeName: 'Latviešu' },
  { code: 'lt-LT', name: 'Lithuanian', nativeName: 'Lietuvių' },
  { code: 'ms-MY', name: 'Malay', nativeName: 'Bahasa Melayu' },
  { code: 'tl-PH', name: 'Filipino', nativeName: 'Filipino' },
  { code: 'sw-KE', name: 'Swahili', nativeName: 'Kiswahili' },
  { code: 'af-ZA', name: 'Afrikaans', nativeName: 'Afrikaans' },
  { code: 'sq-AL', name: 'Albanian', nativeName: 'Shqip' },
  { code: 'hy-AM', name: 'Armenian', nativeName: 'Հայերեն' },
  { code: 'az-AZ', name: 'Azerbaijani', nativeName: 'Azərbaycanca' },
  { code: 'eu-ES', name: 'Basque', nativeName: 'Euskara' },
  { code: 'be-BY', name: 'Belarusian', nativeName: 'Беларуская' },
  { code: 'bs-BA', name: 'Bosnian', nativeName: 'Bosanski' },
  { code: 'ca-ES', name: 'Catalan', nativeName: 'Català' },
  { code: 'ka-GE', name: 'Georgian', nativeName: 'ქართული' },
  { code: 'is-IS', name: 'Icelandic', nativeName: 'Íslenska' },
  { code: 'ga-IE', name: 'Irish', nativeName: 'Gaeilge' },
  { code: 'km-KH', name: 'Khmer', nativeName: 'ខ្មែរ' },
  { code: 'lo-LA', name: 'Lao', nativeName: 'ລາວ' },
  { code: 'mk-MK', name: 'Macedonian', nativeName: 'Македонски' },
  { code: 'mn-MN', name: 'Mongolian', nativeName: 'Монгол' },
  { code: 'ne-NP', name: 'Nepali', nativeName: 'नेपाली' },
  { code: 'si-LK', name: 'Sinhala', nativeName: 'සිංහල' },
  { code: 'uz-UZ', name: 'Uzbek', nativeName: 'Oʻzbekcha' },
  { code: 'cy-GB', name: 'Welsh', nativeName: 'Cymraeg' },
  { code: 'zu-ZA', name: 'Zulu', nativeName: 'isiZulu' },
  { code: 'am-ET', name: 'Amharic', nativeName: 'አማርኛ' },
  { code: 'my-MM', name: 'Burmese', nativeName: 'မြန်မာ' }
];
